# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRevisionBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=128)),
                ('bundle', models.CharField(max_length=128)),
                ('deleted', models.IntegerField()),
                ('entity_id', models.IntegerField()),
                ('revision_id', models.IntegerField()),
                ('language', models.CharField(max_length=32)),
                ('delta', models.IntegerField()),
                ('body_value', models.TextField(blank=True)),
                ('body_summary', models.TextField(blank=True)),
                ('body_format', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'field_revision_body',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldRevisionFieldTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=128)),
                ('bundle', models.CharField(max_length=128)),
                ('deleted', models.IntegerField()),
                ('entity_id', models.IntegerField()),
                ('revision_id', models.IntegerField()),
                ('language', models.CharField(max_length=32)),
                ('delta', models.IntegerField()),
                ('field_tags_tid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'field_revision_field_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('vid', models.IntegerField(blank=True, null=True, unique=True)),
                ('type', models.CharField(max_length=32)),
                ('language', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('uid', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created', models.IntegerField()),
                ('changed', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('promote', models.IntegerField()),
                ('sticky', models.IntegerField()),
                ('tnid', models.IntegerField()),
                ('translate', models.IntegerField()),
            ],
            options={
                'db_table': 'node',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeRevision',
            fields=[
                ('nid', models.IntegerField()),
                ('vid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('log', models.TextField()),
                ('timestamp', models.IntegerField()),
                ('status', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('promote', models.IntegerField()),
                ('sticky', models.IntegerField()),
            ],
            options={
                'db_table': 'node_revision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTermData',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('vid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(blank=True, max_length=255)),
                ('weight', models.IntegerField()),
            ],
            options={
                'db_table': 'taxonomy_term_data',
                'managed': False,
            },
        ),
    ]
